### PR TITLE
Simplify install

### PR DESCRIPTION
**Pull request by oncletom**
- bundle casperjs and phantomjs as Node dependencies
- wrap casperjs call and configure PhantomJS location
- make the wrapper executable from a system point of view through the `bin` property of `package.json`
- update README.md accordingly

### CODE REVIEW

**Comment by BPScott** [comment]
Nice! Yay for encapsulating application level dependancies.

What's the convention for naming executables in node land? I note [node-sass's](https://github.com/sass/node-sass/tree/master/bin) and [grunt's](https://github.com/gruntjs/grunt-cli/tree/master/bin) and [CasperJS's](https://github.com/n1k0/casperjs/tree/master/bin) executables are named after their respective modules. Should we name our executable `bin/gel-test` rather than `bin/cli`?

**Comment by oncletom** [comment]
Hm, well does it matter? Because if the package name is `gel-test`, then even if it is located in `bin/whatever`, Node will make it available as the package name (unless you want to expose multiple executables, but you can still choose their executable names).

Given there is only one executable in that directory, I suppose everybody will find it if they need to propose a change :-D

**Comment by tsouk** [comment]
Nice one Thomas! 
Making this an easily installed testing project, where you can just point to a page and a feature file is the idea. I'll give it a whirl and run the tests we got for typography and pagination.

**Comment by tsouk** [comment]
@oncletom , in my checkout, phantomjs sits next to casperjs and not inside it (hence, I need to change the bin/cli file). Did your casperjs pull in the right version of phantomjs we need, as a dep? I will uninstall everything and start from scratch if so, to test this.

Cheers!

**Comment by BPScott** [comment]
I'm betting that's an npm version 2 vs npm version 3 thing where they're now much better at flattening dependancy graphs.

**Comment by tsouk** [comment]
...or I installed phantomjs in there beforehand. argh!
I'll have to give it a try anyway, now that "gel-test" is in the npm registry 'n all.

**Comment by oncletom** [comment]
@BPScott oh, indeed! This can be addressed by resolving the module location I guess.

**Comment by oncletom** [comment]
I have added a commit to make it compatible with `npm@3` folder structure as well.

This won't work on Windows machine — the script would have to be converted as a node executable to do so.

@tsouk neither phantom nor casperjs have to be installed on a machine beforehand: the above path will look in priority in the bundled phantomjs node module :-)

**Comment by tsouk** [comment]
Works like a charm @oncletom !
I will pull it back and update the gel-test node module.
Thank you for the input guys. Also, as Code:GEL masters, whenever you see features that test a pattern's usability, accessibility and good structure, we can add them here.

**Pull request merged**
